import {
  AreaChart,
  BringToFront,
  CreditCard,
  HandCoins,
  Heart,
  LayoutDashboard,
  User,
  UserRoundPlus,
} from "lucide-react";

export const titles = [
  { key: "mr", label: "Mr" },
  { key: "mrs", label: "Mrs" },
  { key: "miss", label: "Miss" },
];
export const GovernoratesAndCitiesEN = [
  {
    key: "cairo",
    name: "Cairo",
    cities: [
      "Heliopolis",
      "Nasr City",
      "Maadi",
      "Zamalek",
      "Giza",
      "Shubra",
      "Helwan",
      "New Cairo",
      "Bulaq",
      "Ain Shams",
      "El-Marg",
      "El-Matariya",
      "El-Zeitoun",
      "El-Nozha",
      "El-Darb El-Ahmar",
      "El-Khalifa",
      "El-Mosky",
      "El-Sayyeda Zeinab",
      "El-Basatin",
    ],
  },
  {
    key: "alexandria",
    name: "Alexandria",
    cities: [
      "Montaza",
      "Sidi Gaber",
      "Smouha",
      "Mansheya",
      "Borg El Arab",
      "Dekheila",
      "Anfoushi",
      "Agami",
      "El Gomrok",
      "El Max",
      "El Soyof",
      "El Mandara",
      "El Asafra",
    ],
  },
  {
    key: "giza",
    name: "Giza",
    cities: [
      "Dokki",
      "Mohandessin",
      "6th of October",
      "Sheikh Zayed",
      "Faisal",
      "Haram",
      "Imbaba",
      "Kerdasa",
      "Atfih",
      "El Badrashein",
      "Oaseem",
      "El Wahat",
      "Manshiet El Qanater",
      "Badrashin",
      "Saqara",
      "Hawamdia",
      "Ayat",
      "Saff",
    ],
  },
  {
    key: "luxor",
    name: "Luxor",
    cities: [
      "Luxor City",
      "Esna",
      "Armant",
      "New Tiba",
      "Qurna",
      "Bayadeya",
      "El Boghdady",
    ],
  },
  {
    key: "aswan",
    name: "Aswan",
    cities: [
      "Aswan City",
      "Edfu",
      "Kom Ombo",
      "Daraw",
      "Abu Simbel",
      "Kalabsha",
      "El Sibaiya",
      "Nasr El Nuba",
    ],
  },
  {
    key: "ismailia",
    name: "Ismailia",
    cities: [
      "Ismailia City",
      "Fayed",
      "Qantara",
      "Abu Sultan",
      "Tel El Kebir",
      "Abu Sweir",
      "Kasasin",
      "Nefesha",
      "El Temsah",
      "El Salheya",
    ],
  },
  {
    key: "suez",
    name: "Suez",
    cities: [
      "Suez City",
      "Arbaeen",
      "Attaka",
      "Port Tawfiq",
      "Al-Ganayen",
      "Ain Sokhna",
    ],
  },
  {
    key: "port_said",
    name: "Port Said",
    cities: [
      "Port Said City",
      "Port Fuad",
      "El Manzala",
      "Mubarak",
      "El Arab",
      "Gamil",
      "Al-Sharq",
    ],
  },
  {
    key: "red_sea",
    name: "Red Sea",
    cities: [
      "Hurghada",
      "Safaga",
      "Marsa Alam",
      "El Quseir",
      "Shalateen",
      "Halaib",
      "Ras Ghareb",
      "Al Quseir",
      "Safaga",
      "Sharm El Luli",
    ],
  },
  {
    key: "south_sinai",
    name: "South Sinai",
    cities: [
      "Sharm El Sheikh",
      "Dahab",
      "Nuweiba",
      "Taba",
      "Saint Catherine",
      "Ras Sidr",
      "El Tor",
      "Abu Zenima",
      "El Shatt",
    ],
  },
  {
    key: "north_sinai",
    name: "North Sinai",
    cities: [
      "Arish",
      "Sheikh Zuweid",
      "Rafah",
      "Bir El Abd",
      "Hassana",
      "Nakhl",
      "El Qusimah",
      "Bir Gifgafa",
    ],
  },
  {
    key: "qena",
    name: "Qena",
    cities: [
      "Qena City",
      "Nag Hammadi",
      "Qus",
      "Dishna",
      "Abu Tesht",
      "Farshut",
      "Naga' Hammadi",
    ],
  },
  {
    key: "minya",
    name: "Minya",
    cities: [
      "Minya City",
      "Mallawi",
      "Beni Mazar",
      "Maghagha",
      "Deir Mawas",
      "Samalut",
      "Mattay",
      "El Adwa",
      "Abu Qurqas",
    ],
  },
  {
    key: "assuit",
    name: "Assiut",
    cities: [
      "Assiut City",
      "Dayrout",
      "Manfalut",
      "Abnub",
      "El Badari",
      "Abu Tij",
      "El Quseyya",
      "Sahel Selim",
      "Sedfa",
    ],
  },
  {
    key: "sohag",
    name: "Sohag",
    cities: [
      "Sohag City",
      "Akhmim",
      "Girga",
      "Tima",
      "El Balyana",
      "Dar El Salam",
      "Guhayna",
      "Maragha",
      "Tama",
    ],
  },
  {
    key: "beni_suef",
    name: "Beni Suef",
    cities: [
      "Beni Suef City",
      "El Wasta",
      "Nasser",
      "Biba",
      "Fashn",
      "Ehnasia",
      "Sumusta El Waqf",
    ],
  },
  {
    key: "fayoum",
    name: "Fayoum",
    cities: [
      "Fayoum City",
      "Senuris",
      "Tamiya",
      "Ibshaway",
      "Yousef El Seddik",
      "El-Edwa",
      "Etsa",
    ],
  },
  {
    key: "beheira",
    name: "Beheira",
    cities: [
      "Damanhur",
      "Kafr El Dawwar",
      "Rashid",
      "Etay El Barud",
      "Abu Hummus",
      "Shubrakhit",
      "El Mahmoudia",
      "El Rahmaniya",
      "Kom Hamada",
      "Hosh Issa",
    ],
  },
  {
    key: "sharqia",
    name: "Sharqia",
    cities: [
      "Zagazig",
      "10th of Ramadan",
      "Bilbeis",
      "Minya El Qamh",
      "Abu Kabir",
      "Kafr Saqr",
      "Awlad Saqr",
      "Hehia",
      "Mashtoul El Souk",
    ],
  },
  {
    key: "gharbia",
    name: "Gharbia",
    cities: [
      "Tanta",
      "El Mahalla El Kubra",
      "Kafr El Zayat",
      "Zifta",
      "Samannoud",
      "El Santa",
      "Qutur",
      "Basyoun",
    ],
  },
  {
    key: "dakahlia",
    name: "Dakahlia",
    cities: [
      "Mansoura",
      "Talkha",
      "Mit Ghamr",
      "Dikirnis",
      "Bilqas",
      "Aga",
      "Menit El Nasr",
      "Sherbin",
      "Bani Ubaid",
      "El Gamaliya",
      "El Senbellawein",
      "El Kurdi",
      "El Manzala",
      "Mataria",
      "Mitrna",
      "Tamai El Zahayra",
    ],
  },
  {
    key: "kafr_el_sheikh",
    name: "Kafr El Sheikh",
    cities: [
      "Kafr El Sheikh City",
      "Desouk",
      "Fuwah",
      "Baltim",
      "Metobas",
      "Sidi Salem",
      "El Reyad",
      "Bella",
      "Hamoul",
    ],
  },
  {
    key: "monufia",
    name: "Monufia",
    cities: [
      "Shibin El Kom",
      "Sadat City",
      "Menouf",
      "Ashmoun",
      "Tala",
      "Birket El Sab",
      "Quesna",
      "El Bagour",
    ],
  },
  {
    key: "qalyubia",
    name: "Qalyubia",
    cities: [
      "Banha",
      "Qalyub",
      "Shubra El Kheima",
      "Obour",
      "Khosous",
      "Kafr Shukr",
      "Shebin El Qanater",
      "Toukh",
      "Khanka",
    ],
  },
  {
    key: "matruh",
    name: "Matruh",
    cities: [
      "Marsa Matruh",
      "Sidi Barrani",
      "El Alamein",
      "Dabaa",
      "Negila",
      "Salloum",
      "Siwa",
    ],
  },
  {
    key: "new_valley",
    name: "New Valley",
    cities: ["Kharga", "Dakhla", "Farafra", "Balat", "Paris"],
  },
  {
    key: "damietta",
    name: "Damietta",
    cities: [
      "Damietta",
      "New Damietta",
      "Faraskur",
      "Kafr Saad",
      "Zarqa",
      "Ras El Bar",
    ],
  },
];
export const GovernoratesAndCitiesAR = [
  {
    key: "cairo",
    name: "القاهرة",
    cities: [
      "هليوبوليس",
      "مدينة نصر",
      "المعادى",
      "الزمالك",
      "الجيزة",
      "شبرا",
      "حلوان",
      "القاهرة الجديدة",
      "بولاق",
      "عين شمس",
      "المطرية",
      "الزيتون",
      "النزهة",
      "الدرب الأحمر",
      "الخليفة",
      "الموسكي",
      "السيدة زينب",
      "البساتين",
    ],
  },
  {
    key: "alexandria",
    name: "الإسكندرية",
    cities: [
      "المعمورة",
      "سيدي جابر",
      "سموحة",
      "المنشية",
      "برج العرب",
      "الدخيلة",
      "أنفوشي",
      "العجمي",
      "الجمارك",
      "الماكس",
      "السويس",
      "المندرة",
      "الأسافرة",
    ],
  },
  {
    key: "giza",
    name: "الجيزة",
    cities: [
      "الدقي",
      "المهندسين",
      "مدينة 6 أكتوبر",
      "الشيخ زايد",
      "فيصل",
      "الهرم",
      "امبابة",
      "كرداسة",
      "أطفيح",
      "البدرشين",
      "أوسيم",
      "الواحات",
      "منشية القناطر",
      "بدرشين",
      "سقارة",
      "الحوامدية",
      "عيد",
      "صف",
    ],
  },
  {
    key: "luxor",
    name: "الأقصر",
    cities: [
      "مدينة الأقصر",
      "إسنا",
      "أرمنت",
      "طيبة الجديدة",
      "القرنة",
      "بياضية",
      "البغدادي",
    ],
  },
  {
    key: "aswan",
    name: "أسوان",
    cities: [
      "مدينة أسوان",
      "إدفو",
      "كوم أمبو",
      "دراو",
      "أبو سمبل",
      "كلاّبشة",
      "السباعية",
      "ناصر النوبة",
    ],
  },
  {
    key: "ismailia",
    name: "الإسماعيلية",
    cities: [
      "مدينة الإسماعيلية",
      "فايد",
      "قنطرة",
      "أبو سلطان",
      "تل الكبريت",
      "أبو سويف",
      "كساسين",
      "نفشة",
      "التمساح",
      "الصلحية",
    ],
  },
  {
    key: "suez",
    name: "السويس",
    cities: [
      "مدينة السويس",
      "الأربعين",
      "العتاقة",
      "بور توفيق",
      "الجناين",
      "عين شمس",
    ],
  },
  {
    key: "port_said",
    name: "بور سعيد",
    cities: [
      "مدينة بور سعيد",
      "بور فؤاد",
      "المنزلة",
      "مبارك",
      "العرب",
      "جميل",
      "الشرق",
    ],
  },
  {
    key: "red_sea",
    name: "البحر الأحمر",
    cities: [
      "الغردقة",
      "سفاجا",
      "مرسى علم",
      "القصير",
      "شلاتين",
      "حلايب",
      "رأس غارب",
      "القصير",
      "سفاجا",
      "شرم اللولي",
    ],
  },
  {
    key: "south_sinai",
    name: "جنوب سيناء",
    cities: [
      "شرم الشيخ",
      "دهب",
      "نويبع",
      "طابا",
      "سانت كاترين",
      "رأس سدر",
      "الطور",
      "أبو زنيمة",
      "الشاطئ",
    ],
  },
  {
    key: "north_sinai",
    name: "شمال سيناء",
    cities: [
      "العريش",
      "شيخ زويد",
      "رفح",
      "بئر العبد",
      "حسنة",
      "نخل",
      "القصيمة",
      "بئر جفجافة",
    ],
  },
  {
    key: "qena",
    name: "قنا",
    cities: [
      "مدينة قنا",
      "نجع حمادي",
      "قوص",
      "دشنا",
      "أبو تشت",
      "فرشوط",
      "نجع حمادي",
    ],
  },
  {
    key: "minya",
    name: "المنيا",
    cities: [
      "مدينة المنيا",
      "ملوي",
      "بني مزار",
      "مغاغة",
      "دير مواس",
      "سمالوط",
      "ماتاي",
      "العدوة",
      "أبو قرقاص",
    ],
  },
  {
    key: "assuit",
    name: "أسيوط",
    cities: [
      "مدينة أسيوط",
      "ديروط",
      "منفلوط",
      "ابنوب",
      "البدارى",
      "أبو تيج",
      "القوصية",
      "ساحل سليم",
      "سدفا",
    ],
  },
  {
    key: "sohag",
    name: "سوهاج",
    cities: [
      "مدينة سوهاج",
      "أخميم",
      "جرجا",
      "طما",
      "البلينا",
      "دار السلام",
      "جهينة",
      "مراغة",
      "طهطا",
    ],
  },
  {
    key: "beni_suef",
    name: "بني سويف",
    cities: [
      "مدينة بني سويف",
      "الواسطى",
      "ناصر",
      "بيبا",
      "الفشن",
      "إهناسيا",
      "سمسطا",
    ],
  },
  {
    key: "fayoum",
    name: "الفيوم",
    cities: [
      "مدينة الفيوم",
      "سنورس",
      "طامية",
      "إبشواي",
      "يوسف الصديق",
      "العدوة",
      "إطسا",
    ],
  },
  {
    key: "beheira",
    name: "البحيرة",
    cities: [
      "دمنهور",
      "كفر الدوار",
      "رشيد",
      "إيتاي البارود",
      "أبو حمص",
      "شبراخيت",
      "المحمودية",
      "الرحمانية",
      "كوم حمادة",
      "هوش عيسى",
    ],
  },
  {
    key: "sharqia",
    name: "الشرقية",
    cities: [
      "الزقازيق",
      "مدينة 10 رمضان",
      "بلبيس",
      "منيا القمح",
      "أبو كبير",
      "كفر صقر",
      "أولاد صقر",
      "هيهيا",
      "مشتول السوق",
    ],
  },
  {
    key: "gharbia",
    name: "الغربية",
    cities: [
      "طنطا",
      "المحلة الكبرى",
      "كفر الزيات",
      "زفتى",
      "سمنود",
      "السنطة",
      "قطور",
      "بسيون",
    ],
  },
  {
    key: "dakahlia",
    name: "الدقهلية",
    cities: [
      "المنصورة",
      "طلخا",
      "ميت غمر",
      "دكرنس",
      "بلقاس",
      "أجا",
      "منية النصر",
      "شربين",
      "بني عبيد",
      "الجمالية",
      "السنبلاوين",
      "الكردي",
      "المنزلة",
      "المطرية",
      "ميترا",
      "تمى الزهايرة",
    ],
  },
  {
    key: "kafr_el_sheikh",
    name: "كفر الشيخ",
    cities: [
      "مدينة كفر الشيخ",
      "دسوق",
      "فوة",
      "بلطيم",
      "مطوبس",
      "سيدي سالم",
      "الرياد",
      "بيلا",
      "حملول",
    ],
  },
  {
    key: "monufia",
    name: "المنوفية",
    cities: [
      "شبين الكوم",
      "مدينة السادات",
      "منوف",
      "أشمون",
      "تلا",
      "بركة السبع",
      "قويسنا",
      "الباجور",
    ],
  },
  {
    key: "qalyubia",
    name: "القليوبية",
    cities: [
      "بنها",
      "قليوب",
      "شبرا الخيمة",
      "العبور",
      "الخوص",
      "كفر شكر",
      "شبين القناطر",
      "طوخ",
      "خانكة",
    ],
  },
  {
    key: "matruh",
    name: "مطروح",
    cities: [
      "مرسى مطروح",
      "سيدي براني",
      "العلمين",
      "دباء",
      "نجيلة",
      "سلوم",
      "سيوة",
    ],
  },
  {
    key: "new_valley",
    name: "الوادي الجديد",
    cities: ["الخارجة", "داخلة", "فرافرة", "بلاط", "باريس"],
  },
  {
    key: "damietta",
    name: "دمياط",
    cities: [
      "دمياط",
      "دمياط الجديدة",
      "فارسكور",
      "كفر سعد",
      "زرقا",
      "رأس البر",
    ],
  },
];
export const NavbarLinks = [
  {
    title: "about",
    href: "/about-us",
  },
  {
    title: "faqs",
    href: "/faqs",
  },
  {
    title: "tutorial",
    href: "/tutorial",
  },
  {
    title: "register",
    href: "/register/affilite",
  },
  {
    title: "login",
    href: "/login",
  },
];

export const SidebarLinks = [
  {
    title: "dashboard",
    href: "/affilite/dashboard",
    Icon: LayoutDashboard,
  },
  {
    title: "orders",
    href: "/affilite/orders",
    Icon: BringToFront,
  },
  {
    title: "insights",
    href: "/affilite/insights",
    Icon: AreaChart,
  },
  {
    title: "requestConvertCommission",
    href: "/affilite/request-convert-commission",
    Icon: HandCoins,
  },
  {
    title: "payment",
    href: "/affilite/payment",
    Icon: CreditCard,
  },
  {
    title: "profile",
    href: "/affilite/profile",
    Icon: User,
  },
  {
    title: "createModerator",
    href: "/affilite/create/moderator",
    Icon: UserRoundPlus,
  },
  {
    title: "favourites",
    href: "/affilite/favourites",
    Icon: Heart,
  },
];
